name: build

on: push

jobs:
  code:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js 14
        uses: actions/setup-node@v1
        with:
          node-version: "14"

      - name: Install dependencies
        uses: bahmutov/npm-install@v1

      - name: test
        run: yarn test

      - name: build
        run: yarn build
