name: build

on: push

jobs:
  build:
    runs-on: ubuntu-latest
  steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup
      uses: actions/setup-node@v1
      with:
        node-version: 14.x

    - name: Install dependencies
      uses: bahmutov/npm-install@v1

    - name: Test
      run: yarn test

    - name: Build
      run: yarn build
