name: Lint

on: pull_request

jobs:
  code:
    name: Lint code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Install dependencies
        uses: bahmutov/npm-install@v1

      - name: Run ESLint
        run: yarn lint
